### ISSUE TITLE
Board dies after the last BART train leaves

### ISSUE THREAD

**Issue by rfilmyer** [rfilmyer/noiseboard#6]
Probably an issue because the XML data changes when that happens. See attached photo for traceback:

![img_20160501_005959](https://cloud.githubusercontent.com/assets/5913205/14943565/623a0724-0f91-11e6-9126-b72443e2561e.jpg)

**Comment by ghost** [comment]
I will run a cron at around 2am to get a copy of the API response.

**Comment by ghost** [comment]
This is their XML when the API is out of service (It is 3am PDT but the response says 1am), which should be handled as well. I'll still need to get a response that properly shows no trains are in service.

`<root>
<uri>
<![CDATA[ http://api.bart.gov/api/etd.aspx?cmd=etd&orig=16TH ]]>
</uri>
<date>05/03/2016</date>
<time>01:33:03 AM PDT</time>
<station>
<name>16th St. Mission</name>
<abbr>16TH</abbr>
<message>
<error>Updates are temporarily unavailable.</error>
</message>
</station>
<message>
<warning>No data matched your criteria.</warning>
</message>
</root>`

**Comment by rfilmyer** [comment]
Good catch!

**Comment by ghost** [comment]
This should be it: 
`<root>
<uri>
<![CDATA[ http://api.bart.gov/api/etd.aspx?cmd=etd&orig=16TH ]]>
</uri>
<date>05/06/2016</date>
<time>02:37:48 AM PDT</time>
<station>
<name>16th St. Mission</name>
<abbr>16TH</abbr>
</station>
<message>
<warning>No data matched your criteria.</warning>
</message>
</root>`

**Comment by rfilmyer** [comment]
We switched APIs, so no longer a valid issue. Closed.
